// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeguimientoColegio.Web.Data;

#nullable disable

namespace SeguimientoColegio.Web.Data.Migrations
{
    [DbContext(typeof(SeguimientoDbContext))]
    [Migration("20260423003426_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.CorreoOrigen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCorreo")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MessageId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ReferenciaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Remitente")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("Resumen")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("FechaCorreo");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("Remitente");

                    b.ToTable("correos_origen", (string)null);
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("disciplinas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Seguimiento de ejercicios y refuerzos.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Matematicas"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Actividades y materiales de danza.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Danza"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Practicas y materiales de lectoescritura.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Lectoescritura"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Mensajes y actividades de comunicacion.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Comunicacion"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Lecturas y avances.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Plan lector"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Descripcion = "Actividades artisticas.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Arte"
                        });
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.EstadoSeguimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ColorCss")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("Activo", "Orden");

                    b.ToTable("estados_seguimiento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            ColorCss = "#f0b33f",
                            Descripcion = "Registro pendiente de atencion.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Pendiente",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            ColorCss = "#2f80ed",
                            Descripcion = "Registro con avance parcial.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "En proceso",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            ColorCss = "#2f9e44",
                            Descripcion = "Registro completado.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Concluido",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            ColorCss = "#7a828f",
                            Descripcion = "Registro descartado o sin accion.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Descartado",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            ColorCss = "#d64545",
                            Descripcion = "Registro vencido.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Vencido",
                            Orden = 5
                        });
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.EvidenciaRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)");

                    b.Property<int>("RegistroEscolarId")
                        .HasColumnType("int");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("SubidoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("RegistroEscolarId");

                    b.HasIndex("SubidoPorUsuarioId");

                    b.ToTable("evidencias_registro", (string)null);
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.Nino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Alias")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Activo", "Nombres", "Apellidos");

                    b.ToTable("ninos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Alias = "Dani",
                            Apellidos = "Pendiente",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombres = "Daniela"
                        });
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.Plataforma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("plataformas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Actividades interactivas.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Wordwall"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Lecturas y biblioteca digital.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Odilo"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Materiales visuales.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Canva"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Documento PDF.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "PDF"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Videos educativos.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "YouTube"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Descripcion = "Archivos compartidos.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Google Drive"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Descripcion = "Otra plataforma o fuente.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Otro"
                        });
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.Prioridad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ColorCss")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("Activo", "Orden");

                    b.ToTable("prioridades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            ColorCss = "#7f8c8d",
                            Descripcion = "Atencion baja.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Baja",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            ColorCss = "#3d7df0",
                            Descripcion = "Atencion media.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Media",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            ColorCss = "#ef8b2c",
                            Descripcion = "Atencion alta.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Alta",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            ColorCss = "#d64545",
                            Descripcion = "Atencion critica.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Critica",
                            Orden = 4
                        });
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.RegistroAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("CampoModificado")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RegistroEscolarId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("ValorAnterior")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("ValorNuevo")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("RegistroEscolarId", "FechaCreacion");

                    b.ToTable("registro_auditoria", (string)null);
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.RegistroEscolar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ActualizadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("ComentarioGeneral")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int?>("CorreoOrigenId")
                        .HasColumnType("int");

                    b.Property<int>("CreadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int?>("DiasAlerta")
                        .HasColumnType("int");

                    b.Property<int?>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoSeguimientoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("FechaRealizado")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaRecibido")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<int>("NinoId")
                        .HasColumnType("int");

                    b.Property<int?>("PlataformaId")
                        .HasColumnType("int");

                    b.Property<int?>("PrioridadId")
                        .HasColumnType("int");

                    b.Property<bool>("RequiereSeguimiento")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ResponsablePrincipal")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<int>("TipoRegistroId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("varchar(220)");

                    b.HasKey("Id");

                    b.HasIndex("ActualizadoPorUsuarioId");

                    b.HasIndex("CorreoOrigenId");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("EstadoSeguimientoId");

                    b.HasIndex("PlataformaId");

                    b.HasIndex("TipoRegistroId");

                    b.HasIndex("PrioridadId", "FechaActualizacion");

                    b.HasIndex("Activo", "NinoId", "EstadoSeguimientoId");

                    b.HasIndex("FechaRecibido", "FechaVencimiento", "FechaRealizado");

                    b.HasIndex("NinoId", "DisciplinaId", "TipoRegistroId");

                    b.ToTable("registros_escolares", (string)null);
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.RegistroUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("RegistroEscolarId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("RegistroEscolarId", "Orden");

                    b.ToTable("registro_urls", (string)null);
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Gestiona usuarios, catalogos y tiene acceso total.",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Puede crear y actualizar registros y seguimientos.",
                            Nombre = "Editor"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Solo puede revisar la informacion disponible.",
                            Nombre = "Consulta"
                        });
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.TipoRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("tipos_registro", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Material para reforzar aprendizaje.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Material de refuerzo"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Material o accion requerida por el colegio.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Requerimiento"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Lecturas y plan lector.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Lectura"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Tareas con seguimiento.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Tarea"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Aviso relevante para control.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Aviso importante"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Descripcion = "Acuerdos de reuniones presenciales o virtuales.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Acuerdo con profesora"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Descripcion = "Actividad escolar.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Actividad"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Descripcion = "Evaluaciones y pruebas.",
                            FechaActualizacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Evaluacion"
                        });
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.HasIndex("Activo", "RolId");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.EvidenciaRegistro", b =>
                {
                    b.HasOne("SeguimientoColegio.Web.Data.Entities.RegistroEscolar", "RegistroEscolar")
                        .WithMany("Evidencias")
                        .HasForeignKey("RegistroEscolarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeguimientoColegio.Web.Data.Entities.Usuario", "SubidoPorUsuario")
                        .WithMany("EvidenciasSubidas")
                        .HasForeignKey("SubidoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RegistroEscolar");

                    b.Navigation("SubidoPorUsuario");
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.RegistroAuditoria", b =>
                {
                    b.HasOne("SeguimientoColegio.Web.Data.Entities.RegistroEscolar", "RegistroEscolar")
                        .WithMany("Auditoria")
                        .HasForeignKey("RegistroEscolarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeguimientoColegio.Web.Data.Entities.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RegistroEscolar");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.RegistroEscolar", b =>
                {
                    b.HasOne("SeguimientoColegio.Web.Data.Entities.Usuario", "ActualizadoPorUsuario")
                        .WithMany("RegistrosActualizados")
                        .HasForeignKey("ActualizadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeguimientoColegio.Web.Data.Entities.CorreoOrigen", "CorreoOrigen")
                        .WithMany("Registros")
                        .HasForeignKey("CorreoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeguimientoColegio.Web.Data.Entities.Usuario", "CreadoPorUsuario")
                        .WithMany("RegistrosCreados")
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeguimientoColegio.Web.Data.Entities.Disciplina", "Disciplina")
                        .WithMany("Registros")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeguimientoColegio.Web.Data.Entities.EstadoSeguimiento", "EstadoSeguimiento")
                        .WithMany("Registros")
                        .HasForeignKey("EstadoSeguimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeguimientoColegio.Web.Data.Entities.Nino", "Nino")
                        .WithMany("Registros")
                        .HasForeignKey("NinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeguimientoColegio.Web.Data.Entities.Plataforma", "Plataforma")
                        .WithMany("Registros")
                        .HasForeignKey("PlataformaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeguimientoColegio.Web.Data.Entities.Prioridad", "Prioridad")
                        .WithMany("Registros")
                        .HasForeignKey("PrioridadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeguimientoColegio.Web.Data.Entities.TipoRegistro", "TipoRegistro")
                        .WithMany("Registros")
                        .HasForeignKey("TipoRegistroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActualizadoPorUsuario");

                    b.Navigation("CorreoOrigen");

                    b.Navigation("CreadoPorUsuario");

                    b.Navigation("Disciplina");

                    b.Navigation("EstadoSeguimiento");

                    b.Navigation("Nino");

                    b.Navigation("Plataforma");

                    b.Navigation("Prioridad");

                    b.Navigation("TipoRegistro");
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.RegistroUrl", b =>
                {
                    b.HasOne("SeguimientoColegio.Web.Data.Entities.RegistroEscolar", "RegistroEscolar")
                        .WithMany("Urls")
                        .HasForeignKey("RegistroEscolarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroEscolar");
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.Usuario", b =>
                {
                    b.HasOne("SeguimientoColegio.Web.Data.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.CorreoOrigen", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.Disciplina", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.EstadoSeguimiento", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.Nino", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.Plataforma", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.Prioridad", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.RegistroEscolar", b =>
                {
                    b.Navigation("Auditoria");

                    b.Navigation("Evidencias");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.TipoRegistro", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("SeguimientoColegio.Web.Data.Entities.Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("EvidenciasSubidas");

                    b.Navigation("RegistrosActualizados");

                    b.Navigation("RegistrosCreados");
                });
#pragma warning restore 612, 618
        }
    }
}
